# Docker compose configuration for .Net app and database backend
---

version: '2'

services:
  db:
    image: microsoft/mssql-server-linux
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: LetMeInPLZ!!1!
    networks:
      app_net:
        ipv4_address: 172.16.238.2
  app:
    depends_on:
      - db
    build: .
    ports:
      - "80:5000"
    networks:
      app_net:
        ipv4_address: 172.16.238.3

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
