# Docker compose configuration for .Net app and database backend
---

version: '2'

services:
  db:
    image: microsoft/mssql-server-linux
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: LetMeInPLZ!!1!
  app:
    depends_on:
      - db
    build: .
    ports:
      - "80:5000"
